'app: docs':
- changed-files:
  - any-glob-to-any-file: 'apps/docs/*'
'app: web':
  - changed-files:
    - any-glob-to-any-file: 'apps/web/*'
'package: eslint-config':
  - changed-files:
    - any-glob-to-any-file: 'packages/eslint-config/*'
'package: typescript-config':
  - changed-files:
    - any-glob-to-any-file: 'packages/typescript-config/*'
'package: ui':
  - changed-files:
    - any-glob-to-any-file: 'packages/ui/*'
