name-template: 'docs@$RESOLVED_VERSION'
tag-template: 'docs@$RESOLVED_VERSION'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

include-labels:
  - "app: docs"

categories:
  - title: 'ðŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ðŸ§° Maintenance'
    label: 'chore'

autolabeler:
  - label: 'feature'
    branch:
      - '/feat\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes

  $CHANGES
