name: "Pull Request Labeler"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Labeling
      uses: actions/labeler@v5
