name: "Release Drafter"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  docs:
    name: '[docs] Draft release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-configs/docs.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  web:
    name: '[web] Draft release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-configs/web.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
